---

- name: dhcp server is installed
  package:
    name: dhcp
    state: present

- name: directory for dhcp config snippets is present
  file:
    path: /etc/dhcpd.d
    state: directory

- name: dhcp server is configured
  file:
    path: /etc/dhcpd.conf
    state: file

- name: dhcp server is running
  service:
    name: dhcpd
    state: started
